### ISSUE TITLE
Bot stopping after 1 run on VH Event Raid

### ISSUE THREAD

**Issue by jejomar** [steve1316/granblue-automation-android#30]
Provided the log of it. Hope it helps. Thanks

```
00:00:00 ####################
00:00:00 ####################
00:00:00 [FARM] Starting Farming Mode for Event (Token Drawboxes).
00:00:00 [FARM] Farming 30x Repeated Runs at VH Event Raid.
00:00:00 ####################
00:00:00 ####################

00:00:00 [EVENT.TOKEN.DRAWBOXES] Now beginning process to navigate to the mission: VH Event Raid...
00:00:03 [WARNING] Failed to confirm the bot location at HOME.
00:00:03 [INFO] Moving back to the Home screen...

00:00:09 [INFO] Screen Width: 1080, Screen Height: 2340, Screen DPI: 420
00:00:14 [WARNING] Failed to find the CLOSE button.
00:00:30 [WARNING] Failed to confirm the bot location at EVENT_DAILY_MISSIONS.
00:00:32 [EVENT.TOKEN.DRAWBOXES] Now hosting Event Raid...
00:00:42 [WARNING] Failed to confirm the bot location at NOT_ENOUGH_AP.

00:00:42 [INFO] AP auto-restore check passed. Continuing to Party Selection...
00:00:42 Summon list: [huanglong, qilin]
00:00:42 Summon Element list: [misc, misc]
00:00:49 [WARNING] Failed to confirm the bot location at CAPTCHA.

00:00:49 [CAPTCHA] CAPTCHA not detected.
00:00:59 [SUCCESS] Selected Group and Party successfully.

00:01:04 ####################
00:01:04 ####################
00:01:04 [COMBAT] Starting Combat Mode.
00:01:04 ####################
00:01:04 ####################
00:01:11 [COMBAT] Bot has processed the entire combat script. Automatically attacking until the battle ends or Party wipes.
00:01:11 [COMBAT] Bot will now attempt to enable Full Auto...
00:01:14 [WARNING] Failed to find the FULL_AUTO button.
00:01:14 [COMBAT] Bot failed to find the "Full Auto" button. Falling back to Semi Auto...
00:01:14 [COMBAT] Bot will now attempt to enable Semi Auto...
00:01:16 [WARNING] Failed to find the SEMI_AUTO_ENABLED button.
00:01:21 [COMBAT] Semi Auto is now enabled.
00:01:33 [COMBAT] Reloading now.
00:01:38 [COMBAT] Waiting for attack to end...

00:01:45 ####################
00:01:45 ####################
00:01:45 [COMBAT] Ending Combat Mode.
00:01:45 ####################
00:01:45 ####################
00:01:46 [WARNING] Failed to confirm the bot location at LOOT_COLLECTED.
00:01:52 [WARNING] Failed to confirm the bot location at LOOT_COLLECTED.

00:01:57 [INFO] Detecting if any user-specified loot dropped this run...

00:01:57 ********************
00:01:57 ********************
00:01:57 [INFO] Farming Mode: Event (Token Drawboxes)
00:01:57 [INFO] Mission: VH Event Raid
00:01:57 [INFO] Summons: [Huanglong, Qilin]
00:01:57 [INFO] # of runs completed: 1 / 30
00:01:57 ********************
00:01:57 ********************

00:01:57 [INFO] Resting period complete.

00:01:58 [INFO] Now beginning process to check for popups...
00:02:00 GAA encountered an Exception: java.io.FileNotFoundException: headers/event_claim_loot_header.webp
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:881)
	at android.content.res.AssetManager.open(AssetManager.java:858)
	at com.steve1316.granblue_automation_android.utils.ImageUtils.getBitmaps(ImageUtils.kt:433)
	at com.steve1316.granblue_automation_android.utils.ImageUtils.confirmLocation(ImageUtils.kt:665)
	at com.steve1316.granblue_automation_android.utils.ImageUtils.confirmLocation$default(ImageUtils.kt:645)
	at com.steve1316.granblue_automation_android.bot.game_modes.Event.checkEventNightmare(Event.kt:17)
	at com.steve1316.granblue_automation_android.bot.Game.checkForPopups(Game.kt:873)
	at com.steve1316.granblue_automation_android.bot.game_modes.Event.start(Event.kt:294)
	at com.steve1316.granblue_automation_android.bot.Game.startFarmingMode(Game.kt:1078)
	at com.steve1316.granblue_automation_android.utils.BotService$onCreate$1$onTouch$1.invoke(BotService.kt:132)
	at com.steve1316.granblue_automation_android.utils.BotService$onCreate$1$onTouch$1.invoke(BotService.kt:110)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)


Now saving Message Log to file named "log @ 2022-10-02 12:06:16" at /storage/emulated/0/Android/data/com.steve1316.granblue_automation_android/files/logs
```

**Comment by steve1316** [comment]
Fixed in v3.8.1.
